- name: Update repositories cache and install required packages
  apt:
    pkg: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - cron
    - curl
    - software-properties-common

- name: PPA Certbot
  apt_repository: repo='ppa:certbot/certbot' update_cache=yes

- name: Install Certbot
  apt:
    pkg: "python-certbot-nginx"
    state: latest
  become: yes
